name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dockerbuild
      run: (docker build -t my .; docker run my)
    - name: configure
      run: ./configure
    - name: make
      run: (cd build; make)
    - name: make test
      run: (cd build; make test)
